[package]
name = "gcs-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = "4.5.26"
gcp_auth = "0.12.3"
http = "1.2.0"
reqwest = "0.12.12"
serde = "1.0.217"
tokio = { version = "1.43.0", features = ["full"] }
